CI updates

diff --git a/.github/workflows/deploy-to-packagecloud.yml b/.github/workflows/deploy-to-packagecloud.yml
--- a/.github/workflows/deploy-to-packagecloud.yml
+++ b/.github/workflows/deploy-to-packagecloud.yml
@@ -1,48 +1,74 @@
-name: Deploy to Packagecloud
-
+name: Build and Deploy to Packagecloud
 on:
   # Allow manual runs of workflow from Actions tab
   workflow_dispatch:
-
   push:
     branches:
       - main
     paths:
       - 'debian/changelog'
-
+env:
+  debpackagename: wlanpi-profiler
 jobs:
+  check_version:
+    name: Check py & deb pkg versions match
+    uses: WLAN-Pi/gh-workflows/.github/workflows/check-py-deb-pkg-versions-match.yml@main
+    with:
+      python_version_file_path: 'profiler/__version__.py'
+  format:
+    name: Get formatted version for filename
+    uses: WLAN-Pi/gh-workflows/.github/workflows/get-formatted-version-string.yml@main
   sbuild:
-    name: sbuild ${{ matrix.distro }}+${{ matrix.arch }}
-    
-    runs-on: 'ubuntu-22.04'
-
+    name: sbuild ${{ matrix.distro }}+${{ matrix.arch }} pkg
+    runs-on: "${{ vars.RUNS_ON || 'ubuntu-22.04' }}"
+    needs: [format, check_version]
     strategy:
       fail-fast: false
       matrix:
         distro: [bullseye,bookworm]
         arch: [arm64]
-
     environment: PACKAGECLOUD
-
     steps:
+      # - name: Enable debug logging
+      #   run: echo "Debug logging enabled"
+      #   env:
+      #     ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
+      - name: Validate formatted version output
+        run: |
+          if [ -z "${{ needs.format.outputs.version }}" ]; then
+            echo "Error: formatted version output is empty."
+            exit 1 
+          else
+            echo "Formatted version output: ${{ needs.format.outputs.version }}"
+          fi
+      - name: Get current date
+        id: date
+        run: echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_ENV
+      - name: Get package filename
+        run: |
+          echo "filename=${{ env.debpackagename }}_${{ needs.format.outputs.version }}~gha${{ env.date }}+${{ matrix.arch }}_${{ matrix.distro }}" >> $GITHUB_ENV
       - name: Checkout
-        uses: actions/checkout@v3
-
-      - name: sbuild for ${{ matrix.distro }} ${{ matrix.arch }}
+        uses: actions/checkout@v4
+      - name: Validate Environment Variables
+        run: |
+          if [ -z "${{ env.debpackagename }}" ]; then
+            echo "Error: debpackagename cannot be empty"
+            exit 1
+          fi
+        shell: bash
+      - name: sbuild deb pkg for ${{ matrix.distro }}+${{ matrix.arch }}
         uses: wlan-pi/sbuild-debian-package@main
         id: build-debian-package
         with:
           distro: ${{ matrix.distro }}
           arch: ${{ matrix.arch }}
-
       - name: Archive artifacts and upload to GitHub
         uses: actions/upload-artifact@v4
         with:
-          name: wlanpi-profiler-${{ matrix.distro }}-${{ matrix.arch }}
+          name: ${{ env.filename }}
           path: ${{ steps.build-debian-package.outputs.deb-package }}
-
-      - name: Upload armhf package to raspbian/${{ matrix.distro }}
-        if: matrix.arch == 'armhf'
+      - name: Upload armhf pkg to raspbian/${{ matrix.distro }}
+        if: ${{ matrix.arch == 'armhf' && (github.repository_owner == 'WLAN-Pi') }}
         uses: danielmundi/upload-packagecloud@main
         with:
           package-name: ${{ steps.build-debian-package.outputs.deb-package }}
@@ -50,9 +76,8 @@ jobs:
           packagecloud-repo: dev
           packagecloud-distrib: raspbian/${{ matrix.distro }}
           packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
-
-      - name: Upload arm64 package to debian/${{ matrix.distro }}
-        if: matrix.arch == 'arm64'
+      - name: Upload arm64 pkg to debian/${{ matrix.distro }}
+        if: ${{ matrix.arch == 'arm64' && (github.repository_owner == 'WLAN-Pi') }}
         uses: danielmundi/upload-packagecloud@main
         with:
           package-name: ${{ steps.build-debian-package.outputs.deb-package }}
@@ -60,13 +85,12 @@ jobs:
           packagecloud-repo: dev
           packagecloud-distrib: debian/${{ matrix.distro }}
           packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
-  
   slack-workflow-status:
-    if: always()
-    name: Post Workflow Status to Slack
+    if: ${{ always() && (github.repository_owner == 'WLAN-Pi') }}
+    name: Post workflow status to Slack
     needs:
       - sbuild
-    runs-on: 'ubuntu-22.04'
+    runs-on: "${{ vars.RUNS_ON || 'ubuntu-22.04' }}"
     steps:
       - name: Slack Workflow Notification
         uses: Gamesight/slack-workflow-status@master
